# -*- coding: utf-8 -*-
"""One-shot exact-string English pass for ThreeFlow UI / comments."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# Longest strings first
REPLACEMENTS = [
    ("当前场景将被清空,是否继续?", "The current scene will be cleared. Continue?"),
    ("保存场景中,页面可能会有卡顿请耐心等待...", "Saving scene. The page may hitch — please wait..."),
    ("导出场景中,页面可能会有卡顿请耐心等待...", "Exporting scene. The page may hitch — please wait..."),
    ("导出模型中,页面可能会有卡顿请耐心等待...", "Exporting model. The page may hitch — please wait..."),
    ("当前文件大小超过50MB，页面可能会有卡顿", "This file is over 50MB. The page may hitch."),
    ("首次加载需要较长时间，请耐心等待...", "First load can take a while. Please wait..."),
    ("目前仅支持（position,rotation,scale）属性", "Currently only position, rotation, and scale"),
    ("建议使用.gltf格式源,导出模型", "Prefer a .gltf source when exporting"),
    ("支持.jpg,.png,.hdr格式", "Supports .jpg, .png, .hdr"),
    ("当前视角：第一人称", "View: first person"),
    ("当前视角：第三人称", "View: third person"),
    ("拖拽（快捷键：W）", "Move (W)"),
    ("旋转（快捷键：E）", "Rotate (E)"),
    ("缩放（快捷键：R）", "Scale (R)"),
    ("F/鼠标双击材质", "F / double-click mesh"),
    ("长按鼠标右键拖动", "Hold RMB and drag"),
    ("无效的场景文件格式", "Invalid scene file format"),
    ("场景未初始化", "Scene is not initialized"),
    ("文件读取失败", "Failed to read file"),
    ("保存场景成功", "Scene saved"),
    ("保存场景失败", "Failed to save scene"),
    ("导出场景成功", "Scene exported"),
    ("导出场景失败", "Failed to export scene"),
    ("场景导入成功", "Scene imported"),
    ("导入场景失败", "Failed to import scene"),
    ("导出模型成功", "Model exported"),
    ("导出模型失败", "Failed to export model"),
    ("下载成功", "Download complete"),
    ("导入场景中...", "Importing scene..."),
    ("保存场景中...", "Saving scene..."),
    ("初始化数据库失败:", "Failed to initialize database:"),
    ("数据库打开失败", "Failed to open database"),
    ("数据库未初始化", "Database is not initialized"),
    ("添加数据失败", "Failed to add data"),
    ("更新数据失败", "Failed to update data"),
    ("删除数据失败", "Failed to delete data"),
    ("查询数据失败", "Failed to query data"),
    ("创建对象仓库", "Create object store"),
    ("暂无数据", "No data"),
    ("几何体参数", "Geometry"),
    ("项目配置", "Project"),
    ("场景内容", "Scene"),
    ("导入模型", "Import model"),
    ("商用版：ThreeFlowX", "Pro: ThreeFlowX"),
    ("第一人称模式", "First-person mode"),
    ("移动镜头", "Pan camera"),
    ("快捷键", "Hotkeys"),
    ("色调映射", "Tone mapping"),
    ("曝光度", "Exposure"),
    ("模糊度", "Blur"),
    ("渲染器", "Renderer"),
    ("请选择", "Select"),
    ("已加载", "Loaded"),
    ("加载中...", "Loading..."),
    ("作者:answer", "author: answer"),
    ("作者: answer", "author: answer"),
    ("确定", "OK"),
    ("取消", "Cancel"),
    ("提示", "Notice"),
    ("帮助", "Help"),
    ("属性", "Properties"),
    ("材质", "Material"),
    ("动画", "Animation"),
    ("前进", "Forward"),
    ("后退", "Back"),
    ("左移", "Left"),
    ("右移", "Right"),
    ("移动", "Move"),
    ("旋转", "Rotate"),
    ("缩放", "Scale"),
    ("撤销", "Undo"),
    ("重做", "Redo"),
    ("聚焦", "Focus"),
    ("阴影", "Shadows"),
    ("背景", "Background"),
    ("环境", "Environment"),
    ("强度", "Intensity"),
    ("场景", "Scene"),
    ("模型", "Models"),
    ("灯光", "Lights"),
    ("立方体", "Box"),
    ("胶囊", "Capsule"),
    ("圆形", "Circle"),
    ("圆锥", "Cone"),
    ("圆柱", "Cylinder"),
    ("十二面体", "Dodecahedron"),
    ("二十面体", "Icosahedron"),
    ("八面体", "Octahedron"),
    ("平面", "Plane"),
    ("圆环扭结", "Torus knot"),
    ("圆环", "Torus / ring"),
    ("四面体", "Tetrahedron"),
    ("点光源", "Point light"),
    ("平行光源", "Directional light"),
    ("环境光", "Ambient light"),
    ("聚光灯", "Spot light"),
    ("半球光", "Hemisphere light"),
    ("物理材质", "Physical"),
    ("标准材质", "Standard"),
    ("基础材质", "Basic"),
    ("Lambert材质", "Lambert"),
    ("Phong材质", "Phong"),
    ("卡通材质", "Toon"),
    ("法线材质", "Normal"),
    ("深度材质", "Depth"),
    ("Matcap材质", "Matcap"),
    ("线条基础材质", "Line basic"),
    ("虚线材质", "Dashed line"),
    ("点材质", "Points"),
    ("自定义色调映射(CustomToneMapping)", "Custom"),
    ("无色调映射(NoToneMapping)", "None"),
    ("线性色调映射(LinearToneMapping)", "Linear"),
    ("Reinhard色调映射(ReinhardToneMapping)", "Reinhard"),
    ("Cineon色调映射(CineonToneMapping)", "Cineon"),
    ("ACES色调映射(ACESFilmicToneMapping)", "ACES Filmic"),
    ("AgX色调映射(AgXToneMapping)", "AgX"),
    ("Neutral色调映射(NeutralToneMapping)", "Neutral"),
    ("无阴影(NoShadow)", "No shadow (basic)"),
    ("PCF软阴影(PCFShadowMap)", "PCF soft shadow"),
    ("VSM阴影(VSMShadowMap)", "VSM shadow"),
    ("无背景", "None"),
    ("颜色(Color)", "Color"),
    ("图片(Texture)", "Texture"),
    ("雾(FogExp2)", "FogExp2"),
    ("雾(Fog)", "Fog"),
    ("宽度分段", "Width segments"),
    ("高度分段", "Height segments"),
    ("深度分段", "Depth segments"),
    ("半径分段", "Radius segments"),
    ("盖子分段", "Cap segments"),
    ("圆周分段", "Radial segments"),
    ("圆环分段", "Tube segments"),
    ("起始角度", "Start angle"),
    ("中心角", "Sweep angle"),
    ("是否开放", "Open ended"),
    ("是否闭合", "Closed"),
    ("内半径", "Inner radius"),
    ("外半径", "Outer radius"),
    ("底部半径", "Bottom radius"),
    ("顶部半径", "Top radius"),
    ("材质颜色", "Color"),
    ("透明度测试阈值", "Alpha test"),
    ("高光颜色", "Specular"),
    ("高光强度", "Shininess"),
    ("旋转角度", "Rotation"),
    ("织物绒毛效果", "Sheen"),
    ("织物绒毛粗糙度", "Sheen roughness"),
    ("织物绒毛颜色", "Sheen color"),
    ("彩虹色折射率", "Iridescence IOR"),
    ("彩虹色贴图", "Iridescence map"),
    ("彩虹色", "Iridescence"),
    ("深度打包模式", "Depth packing"),
    ("自发光颜色", "Emissive"),
    ("金属度贴图", "Metalness map"),
    ("金属度", "Metalness"),
    ("粗糙度贴图", "Roughness map"),
    ("粗糙度", "Roughness"),
    ("反射率", "Reflectivity"),
    ("折射率", "IOR"),
    ("透光率", "Transmission"),
    ("法线贴图", "Normal map"),
    ("凹凸贴图", "Bump map"),
    ("置换贴图", "Displacement map"),
    ("透明度贴图", "Alpha map"),
    ("环境遮挡贴图", "AO map"),
    ("自发光贴图", "Emissive map"),
    ("光照贴图", "Light map"),
    ("虚线长度", "Dash size"),
    ("虚线间隔", "Gap size"),
    ("点大小", "Point size"),
    ("尺寸衰减", "Size attenuation"),
    ("线框模式", "Wireframe"),
    ("混合模式", "Blending"),
    ("清漆层强度", "Clearcoat"),
    ("清漆层粗糙度", "Clearcoat roughness"),
    ("深度测试", "Depth test"),
    ("深度写入", "Depth write"),
    ("变形目标", "Morph targets"),
    ("法线变形", "Morph normals"),
    ("顶点颜色", "Vertex colors"),
    ("渲染面", "Side"),
    ("透明", "Transparent"),
    ("贴图", "Map"),
    ("线宽", "Line width"),
    ("宽度", "Width"),
    ("高度", "Height"),
    ("深度", "Depth"),
    ("半径", "Radius"),
    ("分段", "Segments"),
    ("细节", "Detail"),
    ("长度", "Length"),
    ("弧度", "Arc"),
    ("路径", "Path"),
    ("球", "Sphere"),
    ("无", "None"),
    ("几何体", "Geometry"),
]

EXTS = {".vue", ".ts", ".js", ".html", ".md", ".scss"}
SKIP_DIRS = {".git", "node_modules", "dist", ".vite", "scripts"}


def should_skip(p: Path) -> bool:
    return any(part in SKIP_DIRS for part in p.parts)


def main() -> None:
    changed = 0
    leftover = []
    for path in ROOT.rglob("*"):
        if not path.is_file() or path.suffix.lower() not in EXTS or should_skip(path):
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except Exception:
            continue
        orig = text
        for zh, en in REPLACEMENTS:
            text = text.replace(zh, en)
        if text != orig:
            path.write_text(text, encoding="utf-8")
            changed += 1
        if any("\u4e00" <= c <= "\u9fff" for c in text):
            leftover.append(str(path.relative_to(ROOT)))
    print(f"updated {changed} files")
    print(f"still have CJK: {len(leftover)}")
    for p in leftover:
        print(p)


if __name__ == "__main__":
    main()
