# -*- coding: utf-8 -*-
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SKIP = {".git", "node_modules", "dist", ".vite"}
EXTS = {".vue", ".ts", ".js", ".html", ".md", ".scss"}

REPL = [
    ("底部占位，防止被商用版文案遮挡", "spacer so the commercial banner does not cover items"),
    ("打开商用版", "open commercial edition"),
    ("选择外部Models", "pick an external model"),
    ("拖拽Models开始", "drag model start"),
    ("拖拽添加各类Models", "drop to add models"),
    ("更新拖拽Models", "update drag model"),
    ("初始化ModelsRenderer", "init model renderer"),
    ("Models加载进度条", "model load progress"),
    ("监听页面加载状态", "listen for page loading"),
    ("提取加载Models的公共方法", "shared model load helper"),
    ("释放创建的URL", "revoke object URL"),
    ("几何Models", "geometry"),
    ("当前拖拽Models", "current drag model"),
    ("加载状态", "loading state"),
    ("变换控制器Models切换", "transform mode switch"),
    ("新增Scene", "new scene"),
    ("保存Scene到indexDb", "save scene to IndexedDB"),
    ("保存Scene快照", "save scene snapshot"),
    ("保存Scene", "save scene"),
    ("导出Scene", "export scene"),
    ("导入Scene", "import scene"),
    ("选择Scenejson", "choose scene JSON"),
    ("导出Models", "export model"),
    ("当前视角", "current view"),
    ("变换控制器类型切换", "switch transform mode"),
    ("格式化Scene数据", "format scene data"),
    ("变换Material随机id", "material refresh id"),
    ("当前变换Materialuuid", "selected object uuid"),
    ("如果未点击选择，则滚动到当前选中节点", "scroll to selected node if not clicked"),
    ("监听变化控制器操作", "listen to transform changes"),
    ("动态设置当前tab", "set current tab"),
    ("监听availableTabs变化", "watch available tabs"),
    ("动态相机相关参数", "camera parameters"),
    ("更新当前Material", "update current material"),
    (".stlModels特殊处理", "STL special case"),
    ("删除Material失败:", "delete failed:"),
    ("删除Material", "delete object"),
    ("复制Material", "copy object"),
    ("双击Material", "double-click object"),
    ("选择Material", "select object"),
    ("更新Material", "update material"),
    ("展开节点", "expand node"),
    ("是否点击选择", "clicked selection"),
    ("当前选中的标签", "current tab"),
    ("控制器事件监听器", "control listeners"),
    ("是否展开", "expanded"),
    ("获取当前Material最新的数据", "latest material data"),
    ("滚动条", "scrollbar"),
    ("树形结构", "tree"),
    ("Lights辅助线", "light helper"),
    ("LightsIntensity范围", "light intensity range"),
    ("更新变换Properties(位置、Rotate、Scale)", "update transform"),
    ("相机单独处理", "camera handled separately"),
    ("更新LightsProperties", "update light properties"),
    ("更新Lights辅助线", "update light helper"),
    ("更新相机Properties", "update camera properties"),
    ("当前选中的Material", "selected object"),
    ("当前Lights", "current light"),
    ("基础Properties", "base properties"),
    ("变换Properties", "transform properties"),
    ("相机Properties", "camera properties"),
    ("播放速度", "playback speed"),
    ("当前播放的Animationuuid", "playing animation uuid"),
    ("当前Models", "current model"),
    ("选择Animation", "choose animation"),
    ("更新Animation参数", "update animation params"),
    ("Animation参数", "animation params"),
    ("颜色和发光颜色需要转换为十六进制", "convert colors to hex"),
    ("如果是Map数据", "if map data"),
    ("添加隐式Properties", "add implicit properties"),
    ("添加下划线前缀以区分", "underscore prefix"),
    ("改变Material类型", "change material type"),
    ("更新MaterialProperties", "update material properties"),
    ("更新MapProperties", "update map properties"),
    ("标记Material需要更新", "mark material dirty"),
    ("上传Map", "upload map"),
    ("获取Map", "get map"),
    ("如果Map可见，则更新Map", "update map if visible"),
    ("更新Map数据", "update map data"),
    ("更新Map", "update map"),
    ("释放旧Material", "dispose old material"),
    ("如果存在旧的Map，释放它", "dispose previous map"),
    ("确保在任何情况下都释放 URL 对象", "always revoke URL"),
    ("获取新的MaterialProperties列表", "rebuild material property list"),
    ("获取当前Material", "current material"),
    ("可编辑的Properties列表", "editable properties"),
    ("生成可编辑的Properties列表", "build editable properties"),
    ("添加MaterialProperties循环", "material property loop"),
    ("Geometry列表", "geometry list"),
    ("更新Geometry", "update geometry"),
    ("更新渲染配置", "update renderer config"),
    ("更新SceneBackground颜色", "update background color"),
    ("更新SceneBackgroundBlur", "update background blur"),
    ("更新SceneBackground", "update scene background"),
    ("更新SceneEnvironment", "update scene environment"),
    ("上传Background图片", "upload background image"),
    ("更新Scene雾", "update scene fog"),
    ("折叠", "collapse"),
    ("开关", "toggle"),
    ("颜色", "color"),
    ("图片", "image"),
    ("预览地址", "preview URL"),
    ("雾近值", "fog near"),
    ("雾远值", "fog far"),
    ("雾密度值", "fog density"),
    ("雾颜色值", "fog color"),
    ("默认Models列表", "default model list"),
    ("默认Geometry列表", "default geometry list"),
    ("默认Lights列表", "default light list"),
    ("Geometry颜色列表", "geometry color list"),
    ("X轴上面的Width", "width on X"),
    ("Y轴上面的Height", "height on Y"),
    ("轴上面的Depth", "depth on Z"),
    ("Width的Segments数", "width segments"),
    ("Height的Segments数", "height segments"),
    ("Depth的Segments数", "depth segments"),
    ("中间区域的Length", "cylinder length"),
    ("构造盖子的曲线部分的个数", "cap curve segments"),
    ("覆盖Capsule圆周的分离的面的个数", "radial faces around capsule"),
    ("Segments（三角面）的数量", "triangle segments"),
    ("第一个Segments的Start angle", "first segment start angle"),
    ("Circle扇区的Sweep angle", "circle sector sweep"),
    ("Cone的Height", "cone height"),
    ("Cone侧面周围的Segments数", "cone side segments"),
    ("指明该Cone的底面是开放的还是封顶的", "whether the cone base is open"),
    ("ModelsProperties可编辑Properties", "editable model properties"),
    ("Geometry边界值配置", "geometry parameter limits"),
    ("通用参数", "common parameters"),
    ("Segments相关", "segment parameters"),
    ("角度相关（Arc制）", "angles (radians)"),
    ("特殊参数", "special parameters"),
    ("颜色选择器配置", "color picker presets"),
    ("Material类型", "material types"),
    ("已自带软Shadows，PCFSoftShadowMap 已弃用", "includes soft shadows; PCFSoftShadowMap is deprecated"),
    ("将旧版 PCFSoftShadowMap 归一为 PCFShadowMap，避免升级后选项None法匹配", "normalize legacy PCFSoftShadowMap to PCFShadowMap"),
    ("历史枚举值为 2", "legacy enum value is 2"),
    ("SceneEnvironment光", "scene environment"),
    ("SceneMap映射类型", "tone mapping types"),
    ("变换控制器类型", "transform control types"),
    ("Geometry枚举", "geometry parameter labels"),
    ("基础Properties", "base properties"),
    ("不Transparent度", "opacity"),
    ("线框Width", "wireframe width"),
    ("高光Material特有", "phong-only"),
    ("精灵Material特有", "sprite-only"),
    ("物理Material特有", "physical-only"),
    ("DepthMaterial特有", "depth-only"),
    ("法线Material特有", "normal-only"),
    ("Environment光和发光", "emissive"),
    ("自发光Intensity", "emissive intensity"),
    ("Environment遮挡Intensity", "AO intensity"),
    ("反射和光泽", "reflection"),
    ("Map相关", "maps"),
    ("线条Material特有", "line-only"),
    ("点Material特有", "points-only"),
    ("特殊效果", "effects"),
    ("标准Material特有", "standard-only"),
    ("Depth和混合", "depth and blending"),
    ("Animation相关", "animation"),
    ("光照计算", "lighting"),
    ("Background类型", "background types"),
    ("Environment类型", "environment types"),
    ("拖拽Models类型", "drag model types"),
    ("Lights图标类型", "light icon types"),
    ("雾类型", "fog types"),
    ("Scene对象名称", "scene object names"),
    ("导出类型", "export types"),
    ("天气类型", "weather types"),
    ("特效类型", "effect types"),
    ("特效参数类型", "effect param types"),
    ("Lights类型", "light types"),
    ("Models类型", "model types"),
    ("文本canvas类型", "text canvas types"),
    ("文本Material类型", "text material types"),
    ("更改Background渐变色为更柔和的色调", "softer background gradient"),
    ("添加图片过渡效果", "image fade"),
    ("更改文字颜色为更柔和的色调", "softer text color"),
    ("添加更柔和的Animation效果", "softer animation"),
    ("添加脉冲Animation关键帧", "pulse keyframes"),
]


def main() -> None:
    leftover = []
    n = 0
    for path in ROOT.rglob("*"):
        if not path.is_file() or path.suffix.lower() not in EXTS:
            continue
        if any(p in SKIP for p in path.parts):
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except Exception:
            continue
        orig = text
        for a, b in REPL:
            text = text.replace(a, b)
        if text != orig:
            path.write_text(text, encoding="utf-8")
            n += 1
        if any("\u4e00" <= c <= "\u9fff" for c in text):
            leftover.append(str(path.relative_to(ROOT)))
    print(f"updated {n}")
    print("leftover", len(leftover))
    for p in leftover:
        print(p)


if __name__ == "__main__":
    main()
